### ISSUE TITLE
Has anyone successfully trained this model?

### ISSUE THREAD

**Issue by Ellen7ions** [HVision-NKU/CamoFormer#11]
I meet nan problem during training :(

**Comment by cdy113** [comment]
> I meet nan problem during training :(

xianzai ne😂

**Comment by Ellen7ions** [comment]
I noticed that I added two sigmoid layers in this network. I remove it, it's ok. 😂
I only tested the model in salient object detection task with pvt_v2_b2 backbone, the result was not good. Maybe the model is not suitable for SOD.
