### ISSUE TITLE
No pretrained model in CamoFormer-trained

### ISSUE THREAD

**Issue by Cheng-Guangliang** [HVision-NKU/CamoFormer#2]
Dear Bowen,

     I found there is no pretrained model (CamoFormer-trained) both in [Baidu Netdisk](https://pan.baidu.com/s/1QyE_HkxCp9vWlhnJAx20dQ?pwd=f4bp), [One Drive](https://mailnankaieducn-my.sharepoint.com/:f:/g/personal/bowenyin_mail_nankai_edu_cn/Eg2fWTz1pjFBiJfAdj1XqGQBbQ2pOjpNq0AbIjseadTgSA?e=BFvBkU). Could you check and update it? Thanks a lot~

**Comment by Yinbowen-chn** [comment]
Thank you for your reminder, I have updated the model file to the network disk.
