### ISSUE TITLE
Question about CamoFormer-R

### ISSUE THREAD

**Issue by CRRCOO** [HVision-NKU/CamoFormer#4]
Nice work! In your paper, the **R** in **CamoFormer-R** is interpreted as **ResNet**. I would like to ask if it refers to use **ResNet-50** as the backbone?

**Comment by Yinbowen-chn** [comment]
Yes. CamoFormer-R is the CamoFormer version with Resnet-50 backbone.

**Comment by CRRCOO** [comment]
Thanks !
