### ISSUE TITLE
PR curves and F-measure curves

### ISSUE THREAD

**Issue by WkangLiu** [HVision-NKU/CamoFormer#5]
Nice work, but I have a question while reading, how did you make your PR curves and F-measure curves, looking forward to your reply!

**Comment by Yinbowen-chn** [comment]
Thanks for your comment! Please refer to this: https://github.com/lartpang/PySODEvalToolkit. We generate our curves using this code.

**Comment by WkangLiu** [comment]
Thanks for your Enthusiastic Reply！I get it.
