### ISSUE TITLE
你好，下载了你给的所有模型的预测图，然后有的压缩包出现错误，解压不成功，能否再次检查一下呢？

### ISSUE THREAD

**Issue by Jack960317** [HVision-NKU/CamoFormer#6]

**Comment by Yinbowen-chn** [comment]
你好，可以具体说一下哪个网盘的哪个模型的预测图压缩包出错了吗？

**Comment by Jack960317** [comment]
> 你好，可以具体说一下哪个网盘的哪个模型的预测图压缩包出错了吗？

**Comment by Jack960317** [comment]
抱歉，还有一个问题，就是CamoFormer-R你给的结果中，CAMO数据集和COD10K数据集的命名是错的，是.jpg.png，建议修改一下，我改了你的命名重新用matlab测，发现这个结果和论文中给的结果出入最大，文中给的结果偏高，谢谢

**Comment by Yinbowen-chn** [comment]
感谢您指出文件文件命名的错误，我会尽快改正并更新。
另外matlab的测试代码速度较慢，python的测试代码相关优化可能做的好一点，速度会快几倍，也可以参考：https://github.com/lartpang/PySODEvalToolkit 。 
不同测试代码结果会有所不同，您可以使用一种测试代码测试所有方法的预测图，并比较相关结果即可。

**Comment by Rapisurazurite** [comment]
模型的预测图, 下载了好几个都打不开
