### ISSUE TITLE
Figure 7中的可视化图

### ISSUE THREAD

**Issue by CRRCOO** [HVision-NKU/CamoFormer#7]
您好，请问论文中Figure 7是如何可视化特征的？

![image](https://user-images.githubusercontent.com/48432056/229462419-4e2e00ae-ff47-41aa-a121-501e87eb7e05.png)

**Comment by Yinbowen-chn** [comment]
十分感谢您的关注，我使用CAM相关方法进行的处理，相关代码：https://github.com/PengtaoJiang/LayerCAM-jittor（LayerCAM），https://github.com/zhoubolei/CAM (CAM), 您可以使用这些方法来生成这种可视化结果图，如有处理上的问题可以随时与我联络。

**Comment by Yinbowen-chn** [comment]
十分感谢您的关注，我使用CAM相关方法进行的处理，相关代码：[https://github.com/PengtaoJiang/LayerCAM-jittor（LayerCAM）和 https://github.com/zhoubolei/CAM](https://github.com/PengtaoJiang/LayerCAM-jittor%EF%BC%88LayerCAM%EF%BC%89%EF%BC%8Chttps://github.com/zhoubolei/CAM) (CAM), 您可以使用这些方法来生成这种可视化结果图，如有处理上的问题可以随时与我联络。

**Comment by CRRCOO** [comment]
收到，非常感谢！
